In [57]:
import requests
import os
import json
import pandas as pd

In [44]:
url = "https://data.sba.gov/api/3/action/datastore_search?resource_id=dc66702f-7eff-4ec0-b998-550ac063ab78&offset="
yearID = ['dc66702f-7eff-4ec0-b998-550ac063ab78','84741c22-bdee-4a0e-b5aa-6a982a85f10b','57cf983a-37e6-495f-80d3-871bef81ad60','7663d46d-09dd-4e54-8542-bbae5f6d3386','553a423b-63ba-4810-9ee3-0ba9f589a6b3','1d3ce89c-0518-4b24-8173-79db32d70de3','41625060-a76b-4608-ad63-d969f0a4bc6f','9b355f56-aa00-462d-9e46-c2f2101d4900']
loans = []
for i in range(0,len(yearID)):
    x=True
    num=0
    while x:
        tempURL = f"https://data.sba.gov/api/3/action/datastore_search?resource_id={yearID[i]}&offset={str(num)}"
        response = requests.get(tempURL)

        j = response.json()
        j = j['result']
        data = j['records']

        if len(data) < 100:
            x = False

        num = num + 100
        loans.append(data)
    
print(len(loans))

93

In [54]:
flatten_list = []
for s in loans:
    for i in s:
        flatten_list.append(i)
len(flatten_list)
flatten_list[3000]

{'_id': 254,
 'SBA Physical Declaration Number': '12100',
 'SBA EIDL Declaration Number': 12101,
 'FEMA Disaster Number': 1895,
 'SBA Disaster Number': 'MA-00025',
 'Damaged Property City Name': 'MEDFORD',
 'Damaged Property Zip Code': 2155,
 'Damaged Property County/Parish Name': 'MIDDLESEX',
 'Damaged Property State Code': 'MA',
 'Total Verified Loss': 98715,
 'Verified Loss Real Estate': 98570,
 'Verified Loss Content': 145,
 'Total Approved Loan Amount': 80400,
 'Approved Amount Real Estate': 75200,
 'Approved Amount Content': 200,
 'Approved Amount EIDL': 5000}

In [58]:
df = pd.DataFrame.from_records(flatten_list)

In [59]:
df

,_id,SBA Physical Declaration Number,SBA EIDL Declaration Number,FEMA Disaster Number,SBA Disaster Number,Damaged Property City Name,Damaged Property Zip Code,Damaged Property County/Parish Name,Damaged Property State Code,Total Verified Loss,Verified Loss Real Estate,Verified Loss Content,Total Approved Loan Amount,Approved Amount Real Estate,Approved Amount Content,Approved Amount EIDL
0,1,11055,11056.0,1730,TX-00265,BOERNE,78006,KENDALL,TX,747912.0,747912.0,0.0,0.0,0.0,0.0,0.0
1,2,11055,11056.0,1730,TX-00265,CASTROVILLE,78009,MEDINA,TX,111171.0,72946.0,38225.0,69700.0,26400.0,26700.0,16600.0
2,3,11055,11056.0,1730,TX-00265,HAMLIN,79520,JONES,TX,4235.0,4235.0,0.0,4300.0,4300.0,0.0,0.0
3,4,11055,11056.0,1730,TX-00265,HOUSTON,77034,HARRIS,TX,57525.0,57525.0,0.0,0.0,0.0,0.0,0.0
4,5,11055,11056.0,1730,TX-00265,MERKEL,79536,TAYLOR,TX,87424.0,76474.0,10950.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8643,526,14474,14475.0,4240,CA-00238,WALLACE,95254,CALAVERAS,CA,76010.0,0.0,76010.0,0.0,0.0,0.0,0.0
8644,527,14484,14485.0,FL-00107,LUTZ,33558,HILLSBOROUGH,FL,17700.0,17700.0,0.0,11800.0,9400.0,0.0,2400.0,NaN
8645,528,14484,14485.0,FL-00107,NEW PORT RICHEY,34655,PASCO,FL,5175.0,0.0,5175.0,0.0,0.0,0.0,0.0,NaN
8646,529,14484,14485.0,FL-00107,ODESSA,33556,HILLSBOROUGH,FL,8237.0,4268.0,3969.0,0.0,0.0,0.0,0.0,NaN
8647,530,14484,14485.0,FL-00107,RIDGE MANOR,33523,PASCO,FL,936.0,936.0,0.0,0.0,0.0,0.0,0.0,NaN